fn main() {
  // println!("cargo:rustc-check-cfg=cfg(desktop)");
  // println!("cargo:rustc-check-cfg=cfg(mobile)");

  // // In plain `cargo check`, TAURI_CONFIG is typically not set.
  // // Running tauri-build in that case may fail because permission files are generated by tauri-cli.
  // if std::env::var("TAURI_CONFIG").is_err() {
  //   return;
  // }

  tauri_build::build()
}
